### ISSUE TITLE
Improve the drawer

### ISSUE THREAD

**Issue by pbochis** [coduno/app#36]
Change the styling for the menu:
- find better fit icons
- Make it bigger

**Comment by lorenzleutgeb** [comment]
@pbochis This issue was never referenced, so it is unclear where it was resolved. Please add a reference at least.

**Comment by pbochis** [comment]
We ditched the drawer in favor of the current menu. Ergo, this is invalid.

**Comment by lorenzleutgeb** [comment]
See, now I know what's going on. That comment was missing.
