### ISSUE TITLE
Change the drawer to top navbar

### ISSUE THREAD

**Issue by victorbalan** [coduno/app#37]
I think it would look more professional and we can add a lot of meaningful icons instead of taking space with a new drawer entry.

**Comment by lorenzleutgeb** [comment]
Could look similar to G+, with search bar at the very top, user-specific buttons/links to the right and a tab switcher centered horizontally.

**Comment by pbochis** [comment]
Please provide a paper mock-up of how the page would look.Take the /tasks route
