### ISSUE TITLE
Add polygon diagram element on coder profile page

### ISSUE THREAD

**Issue by victorbalan** [coduno/app#44]
- [x] Identify chart drawing library to use ([Amcharts](http://www.amcharts.com/demos/radar-chart/#theme-light), [Chart.js](http://www.chartjs.org/), ...?)
- [x] Implement logic that translates `model.Skills` into a chart.
- [x] Actually place chart in coder profile.

**Comment by lorenzleutgeb** [comment]
Could look similar to what [workshape.io](https://www.workshape.io/) are doing.

**Comment by pbochis** [comment]
#58  implements 
- [x] Identify chart drawing library to use Chart.js 
- [x] Implement logic that translates model.Skills into a chart.

**Comment by victorbalan** [comment]
#55 puts the chart on the coder profile
