### ISSUE TITLE
Create profile page for coder

### ISSUE THREAD

**Issue by victorbalan** [coduno/app#51]
![11851019_10207309747606087_1178289037_n](https://cloud.githubusercontent.com/assets/9076766/9199004/8bcbd482-4048-11e5-8e77-3fcb95502d63.jpg)

**Comment by lorenzleutgeb** [comment]
I saw you labeled this `coder`, so just to clarify: We'll first develop the view for companies, and leave coders at the side. That does not mean we ignore the fact that it will be there for coders someday, but it's not needed to implement it fully for coders just now.
