### ISSUE TITLE
Form for creating a task

### ISSUE THREAD

**Issue by pbochis** [coduno/app#60]
The instructions and description for a task will be long and need to be nicely formated, along the lines of this
![coduno1](https://cloud.githubusercontent.com/assets/9076897/9496100/66b7e5de-4c17-11e5-92b3-5592dfc7a033.jpg)

Do we want to have this UI or stick to just manually inserting data in datastore? 
Please discuss

**Comment by lorenzleutgeb** [comment]
What about storing markdown in Datastore and rendering it on the client? This would also be acceptable for instructions that are pulled from Git.

**Comment by lorenzleutgeb** [comment]
If this get's too heavy on formulae, we could switch to PDF.

**Comment by pbochis** [comment]
Regarding markdown, that's what i thought about when i opened this issue

**Comment by lorenzleutgeb** [comment]
> that's what i thought about when i opened this issue

But you did not spell it out :hear_no_evil: :smile:

So yeah, if there's no opposition to MD, that's probably the way to go.
